name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install template
      run: dotnet new --install .
    - name: Create output folder
      run: mkdir output
    - name: Instantiate template
      run: dotnet new f23-angular-material
      working-directory: output
    - name: Build generated .NET code
      run: dotnet build
      working-directory: output
    - name: npm ci
      run: npm ci
      working-directory: output/ClientApp
    - name: npm audit
      run: npm audit
      working-directory: output/ClientApp
    - name: npm run build
      run: npm run build
      working-directory: output/ClientApp
